project:
  type: website
  output-dir: docs

website:
  title: "Ava Robillard"
  favicon: images/favicon.png
  navbar:
    title: false
    logo: images/logo2.png
    #logo-alt: insert description of logo
    right:
      - href: index.qmd
        text: Home
      #- about.qmd
      - posts.qmd
      #- href: resources.qmd
      #  text: Resources
      - icon: github
        href: https://github.com/avarobillard/avarobillard.github.io 
  #page-footer: 
     #left: Copyright 2025, Ava Robillard
     #right: 
      #- icon: github
        #href: https://github.com/avarobillard 

format:
  html:
    theme: styles.scss
    #theme: lux
    toc: true
    page-layout: full
    mainfont: Figtree



